site:
  title: OpenCPN Basics
  url: https://Rasbats.github.io/opencpn-basics/
  start_page: basics-manual::index.adoc

content:
  sources:
   - url: .
     branches: HEAD
 
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
    
output:  
  dir: ./docs
  clean: true
  
#runtime:
#  pull: true
#  cache_dir: ./cache
