site:
  title: OpenCPN Basic
  url: https://Rasbats.github.io/opencpn-basic/

content:
  sources:
   - url: ./
     branches: HEAD
 
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
    
output:  
  dir: ./docs
  clean: true
  
#runtime:
#  pull: true
#  cache_dir: ./cache
